name: Login Flow Test
on:
  push:
    branches: [ "test/**" ]

jobs:
  login-flow-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
      LOCALHOST: ${{ vars.LOCALHOST }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      VITE_BACKEND_BASE_URI: ${{ vars.VITE_BACKEND_BASE_URI }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        base : master
        with:
          filters: |
            logic:
              - '**/*.js'
              - 'package.json'
              - '.github/workflows/login-test.yml'

      - if: steps.changes.outputs.logic == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - if: steps.changes.outputs.logic == 'true'
        run: |
          npm install
          npx playwright install --with-deps
          npx wait-on ${{ vars.VITE_BACKEND_BASE_URI }}
          npm run dev &
          npx wait-on ${{ vars.LOCALHOST }}
          npx playwright test tests/login.test.js

  create-pr:
    needs: login-flow-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: success()
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.AUTO_PR_TOKEN }}
        run: |
          gh pr create \
            --title "Auto PR: ${{ github.ref_name }}" \
            --body "Automated PR from ${{ github.ref_name }}" \
            --base master \
            --head ${{ github.ref_name }}
          sleep 5
          gh pr merge --auto --squash "${{ github.ref_name }}"