name: Login flow test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  login-flow-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install
    - run: npx playwright install --with-deps
    - run: npm run dev &
    - run: npx wait-on http://localhost:5173
    - run : npx wait-on ${{vars.BASE_ENDPOINT}}
    - run: npx playwright test
      env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

